function appendEvent(t, amp, ch, source)
    global events event_indices event_comments event_amplitudes event_channels
    global event_widths event_prominences event_metadata time

    if nargin < 2 || isempty(amp), amp = NaN; end
    if nargin < 3 || isempty(ch), ch = 1; end
    if nargin < 4 || isempty(source), source = 'manual'; end

    t = double(t(1));
    amp = double(amp(1));
    ch = double(ch(1));
    source = char(source);

    idx = 1;
    if ~isempty(time)
        [~, idx] = min(abs(time(:) - t));
    end

    if isempty(events)
        setEventsState(t, ...
            'indices', idx, ...
            'comments', {'...'}, ...
            'amplitudes', amp, ...
            'channels', ch, ...
            'widths', NaN, ...
            'prominences', NaN, ...
            'metadata', createDefaultEventMetadata(source, 1), ...
            'source', source);
        return;
    end

    nOld = numel(events);
    allTimes = [events(:); t];
    allIdx = [padEventColumn(event_indices, nOld, 1); idx];
    allComments = [event_comments(:); {'...'}];
    allAmps = [padEventColumn(event_amplitudes, nOld, NaN); amp];
    allCh = stackEventChannels(event_channels, nOld, ch, 1);
    allW = [padEventColumn(event_widths, nOld, NaN); NaN];
    allP = [padEventColumn(event_prominences, nOld, NaN); NaN];
    allMeta = [normalizeEventMetadata(event_metadata, nOld, 'unknown'); ...
        createDefaultEventMetadata(source, 1)];

    setEventsState(allTimes, ...
        'indices', allIdx, ...
        'comments', allComments, ...
        'amplitudes', allAmps, ...
        'channels', allCh, ...
        'widths', allW, ...
        'prominences', allP, ...
        'metadata', allMeta, ...
        'source', source);
end
