function metadata = createDefaultEventMetadata(source, n)
    metadata = repmat(struct(...
        'source', source, ...
        'method', '', ...
        'data_type', '', ...
        'polarity', '', ...
        'prominence', NaN, ...
        'detection_params', struct()), n, 1);
end
