function [ax, chartAx, h] = createIosPlayerUi(fig, coordsData, assetsPath, playIcon, pauseIcon, recordIcon, stopIcon)
    relativeTags = {'main_axes', 'chart_axes'};
    getElementPosition = @(tag) getGUIElementPosition(coordsData, tag, relativeTags);
    ax = axes(fig, 'Units', 'normalized', 'Position', getElementPosition('main_axes'), 'Tag', 'main_axes');
    chartAx = axes(fig, 'Units', 'normalized', 'Position', getElementPosition('chart_axes'), 'Visible', 'off', 'Tag', 'chart_axes');
    hSlider = uicontrol(fig, 'Style', 'slider', 'Position', getElementPosition('slider'), ...
        'Min', 1, 'Max', 2, 'Value', 1, 'Tag', 'slider');
    hTimeEdit = uicontrol(fig, 'Style', 'edit', 'Position', getElementPosition('time_edit'), ...
        'String', '0:00.0', 'Tag', 'time_edit');
    hNavStart = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('nav_start'), ...
        'String', createIosPlayerIconButtonHTML(fullfile(assetsPath, 'nav_start_btn.png')), 'Tag', 'nav_start');
    hNavPrev = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('nav_prev'), ...
        'String', createIosPlayerIconButtonHTML(fullfile(assetsPath, 'previous_button.png')), 'Tag', 'nav_prev');
    hNavNext = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('nav_next'), ...
        'String', createIosPlayerIconButtonHTML(fullfile(assetsPath, 'next_button.png')), 'Tag', 'nav_next');
    hNavEnd = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('nav_end'), ...
        'String', createIosPlayerIconButtonHTML(fullfile(assetsPath, 'nav_end_btn.png')), 'Tag', 'nav_end');
    hPlayBtn = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('play_btn'), ...
        'String', createIosPlayerIconButtonHTML(playIcon), 'Tag', 'play_btn');
    hSpeedPopup = uicontrol(fig, 'Style', 'popupmenu', 'Position', getElementPosition('speed_popup'), ...
        'String', {'0.5x','1x','2x','5x','10x','20x','50x','100x','200x','500x','1000x'}, 'Value', 2, 'Tag', 'speed_popup');
    hOpenBtn = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('open_btn'), ...
        'String', 'Open', 'Tag', 'open_btn');
    hFilePathText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('file_path_text'), ...
        'String', 'No file opened', 'HorizontalAlignment', 'left', 'FontSize', 8, 'Tag', 'file_path_text');
    hRecordBtn = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('record_btn'), ...
        'String', createIosPlayerIconButtonHTML(recordIcon), 'Tag', 'record_btn');
    hContrastText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('contrast_text'), ...
        'String', 'Contrast:', 'HorizontalAlignment', 'left', 'Tag', 'contrast_text');
    hContrastSlider = uicontrol(fig, 'Style', 'slider', 'Position', getElementPosition('contrast_slider'), ...
        'Min', 0.2, 'Max', 2, 'Value', 1, 'Tag', 'contrast_slider');
    hContrastEdit = uicontrol(fig, 'Style', 'edit', 'Position', getElementPosition('contrast_edit'), ...
        'String', '1.0', 'Tag', 'contrast_edit');
    hGaussianText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('gaussian_text'), ...
        'String', 'Gaussian:', 'HorizontalAlignment', 'left', 'Tag', 'gaussian_text');
    hGaussianSlider = uicontrol(fig, 'Style', 'slider', 'Position', getElementPosition('gaussian_slider'), ...
        'Min', 0, 'Max', 100, 'Value', 3, 'Tag', 'gaussian_slider');
    hGaussianEdit = uicontrol(fig, 'Style', 'edit', 'Position', getElementPosition('gaussian_edit'), ...
        'String', '3.0', 'Tag', 'gaussian_edit');
    hNoiseFilterText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('noise_filter_text'), ...
        'String', 'Noise filter:', 'HorizontalAlignment', 'left', 'Tag', 'noise_filter_text');
    hNoiseFilterPopup = uicontrol(fig, 'Style', 'popupmenu', 'Position', getElementPosition('noise_filter_popup'), ...
        'String', {'None','Median','Wiener','Highpass'}, 'Value', 1, 'Tag', 'noise_filter_popup');
    hColormapText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('colormap_text'), ...
        'String', 'Colormap:', 'HorizontalAlignment', 'left', 'Tag', 'colormap_text');
    hColormapPopup = uicontrol(fig, 'Style', 'popupmenu', 'Position', getElementPosition('colormap_popup'), ...
        'String', {'gray','jet','hot','cool','parula','hsv','spring','summer','autumn','winter','bone','copper','pink','lines'}, 'Value', 1, 'Tag', 'colormap_popup');
    hBlurSigmaText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('blur_sigma_text'), ...
        'String', 'Kernel size:', 'HorizontalAlignment', 'left', 'Visible', 'off', 'Tag', 'blur_sigma_text');
    hBlurSigmaSlider = uicontrol(fig, 'Style', 'slider', 'Position', getElementPosition('blur_sigma_slider'), ...
        'Min', 1, 'Max', 1000, 'Value', 5, 'Visible', 'off', 'Tag', 'blur_sigma_slider');
    hBlurSigmaEdit = uicontrol(fig, 'Style', 'edit', 'Position', getElementPosition('blur_sigma_edit'), ...
        'String', '5', 'Visible', 'off', 'Tag', 'blur_sigma_edit');
    hRotationText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('rotation_text'), ...
        'String', 'Rotation:', 'HorizontalAlignment', 'left', 'Tag', 'rotation_text');
    hRotationSlider = uicontrol(fig, 'Style', 'slider', 'Position', getElementPosition('rotation_slider'), ...
        'Min', -180, 'Max', 180, 'Value', 0, 'Tag', 'rotation_slider');
    hRotationEdit = uicontrol(fig, 'Style', 'edit', 'Position', getElementPosition('rotation_edit'), ...
        'String', '0', 'Tag', 'rotation_edit');
    hOffsetXText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('offset_x_text'), ...
        'String', 'Offset X:', 'HorizontalAlignment', 'left', 'Tag', 'offset_x_text');
    hOffsetXSlider = uicontrol(fig, 'Style', 'slider', 'Position', getElementPosition('offset_x_slider'), ...
        'Min', -200, 'Max', 200, 'Value', 0, 'Tag', 'offset_x_slider');
    hOffsetXEdit = uicontrol(fig, 'Style', 'edit', 'Position', getElementPosition('offset_x_edit'), ...
        'String', '0', 'Tag', 'offset_x_edit');
    hOffsetYText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('offset_y_text'), ...
        'String', 'Offset Y:', 'HorizontalAlignment', 'left', 'Tag', 'offset_y_text');
    hOffsetYSlider = uicontrol(fig, 'Style', 'slider', 'Position', getElementPosition('offset_y_slider'), ...
        'Min', -200, 'Max', 200, 'Value', 0, 'Tag', 'offset_y_slider');
    hOffsetYEdit = uicontrol(fig, 'Style', 'edit', 'Position', getElementPosition('offset_y_edit'), ...
        'String', '0', 'Tag', 'offset_y_edit');
    hZoomText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('zoom_text'), ...
        'String', 'Zoom:', 'HorizontalAlignment', 'left', 'Tag', 'zoom_text');
    hZoomSlider = uicontrol(fig, 'Style', 'slider', 'Position', getElementPosition('zoom_slider'), ...
        'Min', 0.25, 'Max', 4, 'Value', 1, 'Tag', 'zoom_slider');
    hZoomEdit = uicontrol(fig, 'Style', 'edit', 'Position', getElementPosition('zoom_edit'), ...
        'String', '1.0', 'Tag', 'zoom_edit');
    hResetPipelineBtn = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('reset_pipeline_btn'), ...
        'String', 'Reset pipeline', 'Tag', 'reset_pipeline_btn');
    hIosCheck = uicontrol(fig, 'Style', 'checkbox', 'Position', getElementPosition('ios_check'), ...
        'String', 'IOS', 'Value', 0, 'Tag', 'ios_check');
    hBaseStartText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('base_start_text'), ...
        'String', 'Base start:', 'HorizontalAlignment', 'left', 'Visible', 'off', 'Tag', 'base_start_text');
    hBaseStartEdit = uicontrol(fig, 'Style', 'edit', 'Position', getElementPosition('base_start_edit'), ...
        'String', '1', 'Visible', 'off', 'Tag', 'base_start_edit');
    hBaseEndText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('base_end_text'), ...
        'String', 'Base end:', 'HorizontalAlignment', 'left', 'Visible', 'off', 'Tag', 'base_end_text');
    hBaseEndEdit = uicontrol(fig, 'Style', 'edit', 'Position', getElementPosition('base_end_edit'), ...
        'String', '1', 'Visible', 'off', 'Tag', 'base_end_edit');
    hSetBaseBtn = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('set_base_btn'), ...
        'String', 'Set baseframe', 'Visible', 'off', 'Tag', 'set_base_btn');
    hGetTracesBtn = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('get_traces_btn'), ...
        'String', 'Get Traces', 'Tag', 'get_traces_btn');
    hAddReferenceBtn = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('add_reference_btn'), ...
        'String', 'Add Reference', 'Visible', 'off', 'Tag', 'add_reference_btn');
    hDeleteReferenceBtn = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('delete_reference_btn'), ...
        'String', 'Delete Reference', 'Visible', 'off', 'Tag', 'delete_reference_btn');
    hFloatingBaseCheck = uicontrol(fig, 'Style', 'checkbox', 'Position', getElementPosition('floating_base_check'), ...
        'String', 'Floating base', 'Value', 0, 'Visible', 'off', 'Tag', 'floating_base_check');
    hBaseDelayText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('base_delay_text'), ...
        'String', 'Base delay:', 'HorizontalAlignment', 'left', 'Visible', 'off', 'Tag', 'base_delay_text');
    hBaseDelayEdit = uicontrol(fig, 'Style', 'edit', 'Position', getElementPosition('base_delay_edit'), ...
        'String', '1.0', 'Visible', 'off', 'Tag', 'base_delay_edit');
    hReferenceSizeText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('reference_size_text'), ...
        'String', 'Ref Size:', 'HorizontalAlignment', 'left', 'Visible', 'off', 'Tag', 'reference_size_text');
    hReferenceSizeEdit = uicontrol(fig, 'Style', 'edit', 'Position', getElementPosition('reference_size_edit'), ...
        'String', '10', 'Visible', 'off', 'Tag', 'reference_size_edit');
    hReferenceFullSizeCheck = uicontrol(fig, 'Style', 'checkbox', 'Position', getElementPosition('reference_full_size_check'), ...
        'String', 'Full Image Reference', 'Value', 0, 'Visible', 'off', 'Tag', 'reference_full_size_check');
    hAddCursorBtn = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('add_cursor_btn'), ...
        'String', 'Add Cursor', 'Tag', 'add_cursor_btn');
    hIosMinText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('ios_min_text'), ...
        'String', 'IOS Min:', 'HorizontalAlignment', 'left', 'Visible', 'off', 'Tag', 'ios_min_text');
    hIosMinEdit = uicontrol(fig, 'Style', 'edit', 'Position', getElementPosition('ios_min_edit'), ...
        'String', '', 'Visible', 'off', 'Tag', 'ios_min_edit');
    hIosMaxText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('ios_max_text'), ...
        'String', 'IOS Max:', 'HorizontalAlignment', 'left', 'Visible', 'off', 'Tag', 'ios_max_text');
    hIosMaxEdit = uicontrol(fig, 'Style', 'edit', 'Position', getElementPosition('ios_max_edit'), ...
        'String', '', 'Visible', 'off', 'Tag', 'ios_max_edit');
    hCursorsText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('cursors_text'), ...
        'String', 'Cursors:', 'HorizontalAlignment', 'left', 'Tag', 'cursors_text');
    hCursorsTable = uitable(fig, 'Position', getElementPosition('cursors_table'), ...
        'ColumnName', {'#', 'Row', 'Col', 'Size', 'Visible'}, ...
        'ColumnEditable', [false false false true true], ...
        'ColumnFormat', {'numeric', 'numeric', 'numeric', 'numeric', 'logical'}, ...
        'ColumnWidth', {30 80 80 60 60}, ...
        'Data', cell(0, 5), ...
        'Tag', 'cursors_table');
    hEditCursorBtn = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('edit_cursor_btn'), ...
        'String', 'Edit Position', 'Tag', 'edit_cursor_btn');
    hDeleteCursorBtn = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('delete_cursor_btn'), ...
        'String', 'Delete Selected', 'Tag', 'delete_cursor_btn');
    hClearCursorsBtn = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('clear_cursors_btn'), ...
        'String', 'Clear All', 'Tag', 'clear_cursors_btn');
    hShowIosCheck = uicontrol(fig, 'Style', 'checkbox', 'Position', getElementPosition('show_ios_check'), ...
        'String', 'Show IOS', 'Value', 0, 'Tag', 'show_ios_check');
    hClearChartBtn = uicontrol(fig, 'Style', 'pushbutton', 'Position', getElementPosition('clear_chart_btn'), ...
        'String', 'Clear Chart', 'Visible', 'off', 'Tag', 'clear_chart_btn');
    hShowChartCheck = uicontrol(fig, 'Style', 'checkbox', 'Position', getElementPosition('show_chart_check'), ...
        'String', 'Show Chart', 'Value', 1, 'Visible', 'off', 'Tag', 'show_chart_check');
    hChartSmoothText = uicontrol(fig, 'Style', 'text', 'Position', getElementPosition('chart_smooth_text'), ...
        'String', 'Smooth:', 'HorizontalAlignment', 'left', 'Visible', 'off', 'Tag', 'chart_smooth_text');
    hChartSmoothEdit = uicontrol(fig, 'Style', 'edit', 'Position', getElementPosition('chart_smooth_edit'), ...
        'String', '1', 'Visible', 'off', 'Tag', 'chart_smooth_edit');
    h = buildGuiHandles(fig, getIosPlayerGuiHandleTags());
end
