function gfx = emptyMainPlotGfx()
gfx = struct( ...
    'traceLines', gobjects(0), ...
    'gapLines', gobjects(0), ...
    'csdImage', gobjects(0), ...
    'muaImage', gobjects(0), ...
    'muaScatter', gobjects(0), ...
    'signature', []);
end
