function gfx = emptyMainPlotGfx()
gfx = struct( ...
    'traceLines', gobjects(0), ...
    'gapLines', gobjects(0), ...
    'csdImage', gobjects(0), ...
    'muaImage', gobjects(0), ...
    'muaScatter', gobjects(0), ...
    'eventLines', gobjects(0), ...
    'stimLines', gobjects(0), ...
    'eventLabels', gobjects(0), ...
    'eventLabelRects', gobjects(0), ...
    'stimLabels', gobjects(0), ...
    'stimLabelRects', gobjects(0), ...
    'modeLabel', gobjects(0), ...
    'titleHandle', gobjects(0), ...
    'ampTexts', gobjects(0), ...
    'ampScatters', gobjects(0), ...
    'scaleBars', gobjects(0), ...
    'signature', []);
end
