function gfx = emptyChannelGridGfx()
gfx = struct( ...
    'host', gobjects(0), ...
    'layout', [], ...
    'axes', gobjects(0), ...
    'size', [0 0], ...
    'spacing', '', ...
    'indexGrid', [], ...
    'traceLines', gobjects(0), ...
    'nameLabels', gobjects(0), ...
    'eventLines', {{}}, ...
    'stimLines', {{}}, ...
    'eventLabels', gobjects(0), ...
    'eventLabelRects', gobjects(0), ...
    'stimLabels', gobjects(0), ...
    'stimLabelRects', gobjects(0), ...
    'centerLabel', gobjects(0), ...
    'scaleBars', gobjects(0));
end
