function ensureSlopeMeasurementSettings()
%ENSURESLOPEMEASUREMENTSETTINGS Analysis-only measurement settings with defaults.

    global slope_measurement_settings

    defaults = struct( ...
        'channel', 1, ...
        'baseline_start', 0, ...
        'baseline_end', 0, ...
        'peak_start', 0, ...
        'peak_end', 0, ...
        'slope_percent', 20, ...
        'peak_polarity', 'positive', ...
        'onset_method', 'derivative', ...
        'onset_threshold', 3, ...
        'show_baseline', true, ...
        'show_onset', true, ...
        'show_slope', true, ...
        'show_peak', true);

    if isempty(slope_measurement_settings) || ~isstruct(slope_measurement_settings)
        slope_measurement_settings = defaults;
        return;
    end

    for fn = fieldnames(defaults)'
        if ~isfield(slope_measurement_settings, fn{1})
            slope_measurement_settings.(fn{1}) = defaults.(fn{1});
        end
    end
end
