function defaults = getDefaultGlobalSettings()
    defaults = struct();
    defaults.lastOpenedFiles = {};
    defaults.figure_position = [20 60 1280 650] * 0.8;
    defaults.timeUnitFactor = 1000;
    defaults.selectedUnit = 'ms';
    defaults.art_rem_settings = struct('artifact_window_ms', 0, 'interp_method', 'linear');
    defaults.add_event_settings = [];
    defaults.autodetection_settings = [];
    defaults.import_settings = struct();
    defaults.lines_and_styles = [];
    defaults.auto_open_last_file = true;
    defaults.visualSettings = struct( ...
        'show_full_signal', true, ...
        'show_amplitude_labels', false, ...
        'show_scale_bars', true, ...
        'auto_shift', true, ...
        'side_panel_visible', true, ...
        'stim_show', true, ...
        'show_spikes', false, ...
        'show_CSD', false, ...
        'viewer_display_mode', 'linear');
    defaults.cursor_positions = struct();
end
