function hT = hylabel_ax(x, ax, mytext, lineStyle)
if nargin < 4 || isempty(lineStyle)
    lineStyle = struct( ...
        'LabelColor', 'k', ...
        'LabelFontSize', 11, ...
        'LabelFontWeight', 'bold', ...
        'LabelBackgroundColor', 'none');
end

% Добавление текста
hT = text(x, ax.YLim(2), mytext, ...
    'VerticalAlignment', 'bottom', ...
    'HorizontalAlignment', 'center', ...
    'Interpreter', 'none', ...
    'FontWeight', lineStyle.LabelFontWeight, ...
    'FontSize', lineStyle.LabelFontSize, ...
    'Color', lineStyle.LabelColor, ...
    'BackgroundColor', lineStyle.LabelBackgroundColor);
end
