function hT = hylabel_ax(x, ax, mytext, lineStyle, centerText)
if nargin < 4 || isempty(lineStyle)
    lineStyle = struct( ...
        'LabelColor', 'k', ...
        'LabelFontSize', 11, ...
        'LabelFontWeight', 'bold', ...
        'LabelBackgroundColor', 'none');
end
if nargin < 5 || isempty(centerText)
    centerText = false;
end

textHorizontalAlignment = 'left';
if centerText
    textHorizontalAlignment = 'center';
end

% Добавление текста
hT = text(x, ax.YLim(2), mytext, ...
    'VerticalAlignment', 'bottom', ...
    'HorizontalAlignment', textHorizontalAlignment, ...
    'Interpreter', 'none', ...
    'FontWeight', lineStyle.LabelFontWeight, ...
    'FontSize', lineStyle.LabelFontSize, ...
    'Color', lineStyle.LabelColor, ...
    'BackgroundColor', lineStyle.LabelBackgroundColor);
end
