function defs = iosPlayerPipelineParamDefs()
    defs = struct( ...
        'stateField', {'rotationAngle', 'offsetX', 'offsetY', 'zoomFactor', 'gaussianSigma', ''}, ...
        'sliderKey', {'rotationSlider', 'offsetXSlider', 'offsetYSlider', 'zoomSlider', 'gaussianSlider', 'contrastSlider'}, ...
        'editKey', {'rotationEdit', 'offsetXEdit', 'offsetYEdit', 'zoomEdit', 'gaussianEdit', 'contrastEdit'}, ...
        'min', {-180, -200, -200, 0.25, 0, 0.2}, ...
        'max', {180, 200, 200, 4, 100, 2}, ...
        'format', {'%.1f', '%.0f', '%.0f', '%.2f', '%.2f', '%.2f'}, ...
        'round', {false, true, true, false, false, false}, ...
        'default', {0, 0, 0, 1, 3, 1}, ...
        'clearBaseframe', {false, false, false, false, true, false}, ...
        'refreshMode', {'frame', 'frame', 'frame', 'frame', 'frame', 'contrast'}, ...
        'editRejectBelowMin', {false, false, false, true, true, true});
end
