function s = iosPlayerDefaultPipelineState()
    s = struct( ...
        'rotationAngle', 0, ...
        'offsetX', 0, ...
        'offsetY', 0, ...
        'zoomFactor', 1, ...
        'gaussianSigma', 3, ...
        'noiseFilterType', 'none', ...
        'noiseFilterParam', 5);
end
