function h = loadingOverlay(parent, visible)
%LOADINGOVERLAY Compact centered LOADING label on a panel/figure.
%   loadingOverlay(parent, true)  — show + drawnow
%   loadingOverlay(parent, false) — hide

if nargin < 2
    visible = true;
end

h = gobjects(0);
ov = getappdata(parent, 'loadingOverlay');
have = ~isempty(ov) && isgraphics(ov);

if ~visible
    if have
        set(ov, 'Visible', 'off');
        h = ov;
    end
    return;
end

if ~have
    delete(findall(parent, 'Tag', 'loadingOverlay'));
    delete(findall(parent, 'Tag', 'viewerLoadingText'));
    delete(findall(parent, 'Tag', 'viewerLoadingAx'));
    ov = uicontrol( ...
        'Parent', parent, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'Position', [1 1 10 10], ...
        'String', 'LOADING...', ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 12, ...
        'FontWeight', 'normal', ...
        'ForegroundColor', [0 0 0], ...
        'BackgroundColor', [0.8 0.8 0.8], ...
        'HitTest', 'off', ...
        'Tag', 'loadingOverlay', ...
        'Visible', 'off');
    setappdata(parent, 'loadingOverlay', ov);
end

panelPix = getpixelposition(parent);
set(ov, ...
    'Units', 'pixels', ...
    'String', 'LOADING...', ...
    'Visible', 'on');
ext = get(ov, 'Extent');
w = ext(3) + 12;
ht = ext(4) + 4;
set(ov, 'Position', [ ...
    max(1, (panelPix(3) - w) / 2), ...
    max(1, (panelPix(4) - ht) / 2), ...
    w, ht]);
uistack(ov, 'top');
drawnow;
h = ov;
end
