function saveChannelSettings()
    % SAVECHANNELSETTINGS Сохраняет настройки каналов в файл
    % Использует глобальные переменные для получения данных
    
    % Глобальные переменные
    global matFilePath newFs shiftCoeff time_forward time_back
    global channelNames channelEnabled scalingCoefficients colorsIn lineCoefficients
    global mean_group_ch csd_avaliable filter_avaliable baseline_subtract_available filterSettings
    global stims EV_version channelTable csd_smooth_coef csd_contrast_coef
    
    % Проверяем, что файл существует
    if exist(matFilePath, 'file') == 2
        % Получаем путь к файлу настроек
        [path, name, ~] = fileparts(matFilePath);
        channelSettingsFilePath = fullfile(path, [name '_channelSettings.stn']);
        
        % Получаем данные из таблицы каналов если доступна
        if exist('channelTable', 'var') && ~isempty(channelTable) && ishandle(channelTable)
            channelSettings = get(channelTable, 'Data');
        else
            channelSettings = [];
        end
        
        % Сохраняем настройки с флагом -append
        save(channelSettingsFilePath, ...
            'channelSettings', ...% для совместимости со старыми версиями
            'newFs', ...
            'shiftCoeff', ...
            'time_forward', ...
            'time_back', ...
            'filterSettings', ...
            'csd_smooth_coef', ...
            'csd_contrast_coef', ...
            'channelNames', ...
            'channelEnabled', ...
            'scalingCoefficients', ...
            'colorsIn', ...
            'lineCoefficients', ...
            'mean_group_ch', ...
            'csd_avaliable', ...
            'filter_avaliable', ...
            'baseline_subtract_available', ...
            'stims', ...
            'EV_version');
    end
end
