function showMarkdownHelp(markdownFile)
    % SHOWMARKDOWNHELP Отображает markdown файл в системном браузере
    %   showMarkdownHelp(markdownFile) - отображает markdown файл
    %   
    %   Параметры:
    %       markdownFile - путь к markdown файлу (.md)
    
    if ~exist(markdownFile, 'file')
        errordlg(['Файл не найден: ' markdownFile], 'Ошибка');
        return;
    end
    
    [filePath, fileName, ~] = fileparts(markdownFile);
    htmlFile = fullfile(filePath, [fileName '.html']);
    
    if ~exist(htmlFile, 'file')
        markdownContent = fileread(markdownFile);
        htmlContent = markdownToHtml(markdownContent);
        
        fid = fopen(htmlFile, 'w', 'n', 'UTF-8');
        fprintf(fid, '%s', htmlContent);
        fclose(fid);
    end
    
    web(htmlFile, '-browser');
end

function htmlContent = markdownToHtml(markdownText)
    % MARKDOWNTOHTML Конвертирует markdown в HTML используя JavaScript
    
    escapedMarkdown = escapeForJavaScript(markdownText);
    
    htmlTemplate = ['<!DOCTYPE html>' newline ...
        '<html><head>' newline ...
        '<meta charset="UTF-8">' newline ...
        '<script src="../functions/showdown.min.js"></script>' newline ...
        '<style>' newline ...
        'body { font-family: Arial, sans-serif; padding: 20px; line-height: 1.6; }' newline ...
        'h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }' newline ...
        'h2 { color: #34495e; margin-top: 30px; }' newline ...
        'h3 { color: #7f8c8d; }' newline ...
        'code { background-color: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-family: "Courier New", monospace; }' newline ...
        'pre { background-color: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; }' newline ...
        'pre code { background-color: transparent; padding: 0; }' newline ...
        'a { color: #3498db; text-decoration: none; }' newline ...
        'a:hover { text-decoration: underline; }' newline ...
        'ul, ol { margin-left: 20px; }' newline ...
        'blockquote { border-left: 4px solid #3498db; padding-left: 15px; margin-left: 0; color: #7f8c8d; }' newline ...
        'table { border-collapse: collapse; width: 100%%; margin: 20px 0; }' newline ...
        'table th, table td { border: 1px solid #ddd; padding: 8px; text-align: left; }' newline ...
        'table th { background-color: #3498db; color: white; }' newline ...
        '</style>' newline ...
        '</head><body>' newline ...
        '<div id="content"></div>' newline ...
        '<script>' newline ...
        'var converter = new showdown.Converter();' newline ...
        'converter.setOption("tables", true);' newline ...
        'converter.setOption("strikethrough", true);' newline ...
        'converter.setOption("tasklists", true);' newline ...
        'var markdown = %s;' newline ...
        'var html = converter.makeHtml(markdown);' newline ...
        'document.getElementById("content").innerHTML = html;' newline ...
        '</script>' newline ...
        '</body></html>'];
    
    htmlContent = sprintf(htmlTemplate, escapedMarkdown);
end

function escaped = escapeForJavaScript(text)
    escaped = jsonencode(text);
end

