function showAboutProgram()
    % SHOWABOUTPROGRAM Отображает окно с информацией о программе
    
    global EV_version EV_date EV_author EV_email EV_description
    
    existingFig = findobj('Tag', 'AboutProgram');
    if ~isempty(existingFig)
        figure(existingFig);
        return;
    end
    
    screenSize = get(0, 'ScreenSize');
    windowWidth = 500;
    windowHeight = 300;
    xPos = (screenSize(3) - windowWidth) / 2;
    yPos = (screenSize(4) - windowHeight) / 2;
    
    fig = figure('Name', 'About Easy Viewer', ...
                 'NumberTitle', 'off', ...
                 'MenuBar', 'none', ...
                 'ToolBar', 'none', ...
                 'Position', [xPos, yPos, windowWidth, windowHeight], ...
                 'Resize', 'off', ...
                 'Tag', 'AboutProgram', ...
                 'CloseRequestFcn', @closeWindow);
    
    uicontrol('Parent', fig, 'Style', 'text', ...
              'String', 'Easy Viewer', ...
              'Position', [50, 240, 400, 30], ...
              'HorizontalAlignment', 'center', ...
              'FontWeight', 'bold', ...
              'FontSize', 18, ...
              'ForegroundColor', [0, 0.4, 0.8]);
    
    versionStr = sprintf('Version: %s', EV_version);
    uicontrol('Parent', fig, 'Style', 'text', ...
              'String', versionStr, ...
              'Position', [50, 210, 400, 20], ...
              'HorizontalAlignment', 'center', ...
              'FontSize', 11);
    
    descriptionStr = sprintf('%s', EV_description);
    uicontrol('Parent', fig, 'Style', 'text', ...
              'String', descriptionStr, ...
              'Position', [50, 180, 400, 20], ...
              'HorizontalAlignment', 'center', ...
              'FontSize', 10, ...
              'ForegroundColor', [0.5, 0.5, 0.5]);
    
    authorStr = sprintf('Author: %s', EV_author);
    uicontrol('Parent', fig, 'Style', 'text', ...
              'String', authorStr, ...
              'Position', [50, 140, 400, 20], ...
              'HorizontalAlignment', 'center', ...
              'FontSize', 10);
    
    emailStr = sprintf('Email: %s', EV_email);
    uicontrol('Parent', fig, 'Style', 'text', ...
              'String', emailStr, ...
              'Position', [50, 115, 400, 20], ...
              'HorizontalAlignment', 'center', ...
              'FontSize', 10);
    
    dateStr = sprintf('Date: %s', EV_date);
    uicontrol('Parent', fig, 'Style', 'text', ...
              'String', dateStr, ...
              'Position', [50, 90, 400, 20], ...
              'HorizontalAlignment', 'center', ...
              'FontSize', 10);
    
    uicontrol('Parent', fig, 'Style', 'pushbutton', ...
              'String', 'Close', ...
              'Position', [200, 30, 100, 35], ...
              'Callback', @closeWindow, ...
              'FontSize', 11);
    
    function closeWindow(~, ~)
        delete(fig);
    end
end

