function updateViewerPlotTitle(titleLabel, centerLabel, modeColor, modeBgColor)
%UPDATEVIEWERPLOTTITLE Shared file title + Mode on header axes in plot_panel.

global multiax

if nargin < 2
    centerLabel = '';
end
if nargin < 3 || isempty(modeColor)
    modeColor = [0 0.4 0];
end
if nargin < 4 || isempty(modeBgColor)
    modeBgColor = 'none';
end

plotPanel = get(multiax, 'Parent');
hdr = getappdata(plotPanel, 'viewerPlotHeader');
needInit = isempty(hdr) || ~isstruct(hdr) ...
    || ~isfield(hdr, 'ax') || ~isgraphics(hdr.ax) ...
    || ~isfield(hdr, 'title') || ~isgraphics(hdr.title) ...
    || ~isfield(hdr, 'mode') || ~isgraphics(hdr.mode);

if needInit
    delete(findall(plotPanel, 'Tag', 'viewerPlotHeaderAx'));
    delete(findall(plotPanel, 'Tag', 'viewerPlotTitle'));
    delete(findall(plotPanel, 'Tag', 'viewerPlotMode'));

    axHeader = axes( ...
        'Parent', plotPanel, ...
        'Units', 'normalized', ...
        'Position', [0 0.90 1 0.10], ...
        'Visible', 'off', ...
        'HitTest', 'off', ...
        'HandleVisibility', 'off', ...
        'XLim', [0 1], ...
        'YLim', [0 1], ...
        'XTick', [], ...
        'YTick', [], ...
        'Tag', 'viewerPlotHeaderAx');
    hold(axHeader, 'on');

    hTitle = text(axHeader, 0.08, 0.28, '', ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'middle', ...
        'FontWeight', 'bold', ...
        'FontSize', 11, ...
        'Interpreter', 'none', ...
        'HitTest', 'off', ...
        'Clipping', 'off', ...
        'Tag', 'viewerPlotTitle');

    hMode = text(axHeader, 0.5, 0.78, '', ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontWeight', 'bold', ...
        'FontSize', 11, ...
        'Interpreter', 'none', ...
        'Clipping', 'off', ...
        'HitTest', 'on', ...
        'PickableParts', 'all', ...
        'Tag', 'viewerPlotMode', ...
        'ButtonDownFcn', @viewerModeLabelClick);

    hdr = struct('ax', axHeader, 'title', hTitle, 'mode', hMode);
    setappdata(plotPanel, 'viewerPlotHeader', hdr);
    uistack(axHeader, 'top');
end

set(hdr.ax, 'Position', [0 0.90 1 0.10]);
set(hdr.title, ...
    'Position', [0.08 0.28 0], ...
    'String', titleLabel, ...
    'Visible', 'on');
set(hdr.mode, ...
    'Position', [0.5 0.78 0], ...
    'String', centerLabel, ...
    'Color', modeColor, ...
    'BackgroundColor', modeBgColor, ...
    'Visible', 'on', ...
    'ButtonDownFcn', @viewerModeLabelClick);
uistack(hdr.ax, 'top');
end
