function result = autoMeanStimulus(filePath, fileId, params)
    global zav_calling autodetection_settings timeUnitFactor
    
    metadata = zav_calling(filePath);
    if isempty(metadata)
        result = [];
        return
    end

    buildFigure = params.buildFigure;
    opts = struct('autoScale', params.autoScale, 'xLimits', params.xLimits, 'showOriginalTraces', params.showOriginalTraces, 'removeBaseline', params.removeBaseline, 'removeArtifact', params.removeArtifact, 'artifactWindow_ms', params.artifactWindow_ms, 'SmoothingKernel_s', params.SmoothingKernel_s, 'SubtractMean', params.SubtractMean);
    [calcResult, plotParams] = calculateMeanEvents('stimuli', opts);

    detParams = struct('Polarity', params.Polarity, ...
        'MinPeakProminence', params.MinPeakProminence, ...
        'MinPeakDistance', params.MinPeakDistance_s * timeUnitFactor, ...
        'MaxPeakWidth', params.MaxPeakWidth_s * timeUnitFactor, ...
        'SmoothingKernel_s', params.SmoothingKernel_s * timeUnitFactor);

    events = detectPeaksInOriginalData(calcResult, detParams);

    figPath = '';
    if buildFigure
        figPath = plotMeanStimulusFullResult(calcResult, plotParams, events, metadata, params);
    end
    
    result = struct( ...
        'module_name', 'autoMeanStimulus', ...
        'module_display_name', 'Auto Mean Stimulus', ...
        'module_description', 'Автоусреднение стимулов', ...
        'report_path', figPath, ...
        'parameters', params, ...
        'calcResult', calcResult, ...
        'events', events, ...
        'tableResultInsert', {{'events.first_onset_by_channel', 'events.median_first_onset', 'events.paired_ttest_pvalue_by_channel', 'events.has_response_mean', 'events.median_amplitude_before_zero', 'events.median_amplitude_after_zero'}});
end

