function app()
    % Создаем главное окно
    f = figure('Name', 'EasyViewer App', ...
              'NumberTitle', 'off', ...
              'MenuBar', 'none', ...
              'ToolBar', 'none', ...
              'Position', [100, 100, 400, 300]);
    
    % Создаем панель для кнопок
    panel = uipanel('Parent', f, ...
                   'Position', [0.1, 0.1, 0.8, 0.8]);
    
    % Кнопка для запуска EasyView
    uicontrol('Parent', panel, ...
             'Style', 'pushbutton', ...
             'String', 'Signal Viewer', ...
             'Position', [40, 120, 240, 60], ...
             'FontSize', 14, ...
             'Callback', @(~,~)EasyView());
    
    % Кнопка для запуска signalAnalysisGUI
    uicontrol('Parent', panel, ...
             'Style', 'pushbutton', ...
             'String', 'Signal Analysis', ...
             'Position', [40, 40, 240, 60], ...
             'FontSize', 14, ...
             'Callback', @(~,~)signalAnalysisGUI());
end 