function buildFullInstaller()
    p = getDeployPaths();
    appExe = fullfile(p.applicationDir, 'EasyView.exe');
    if ~isfile(appExe)
        error('Run deploy/buildApplication first: %s not found', appExe);
    end

    splashPath = fullfile(p.applicationDir, 'splash.png');
    if ~isfile(splashPath)
        splashSrc = fullfile(p.resources, 'app_splash.png');
        if ~isfile(splashSrc)
            splashSrc = fullfile(p.resources, 'splash.png');
        end
        copyfile(splashSrc, splashPath);
    end

    description = ['Easy Viewer is a software developed for viewing electrophysiological data. ', ...
        'It supports .mat format files, allowing users to view Local Field Potentials (LFP), ', ...
        'Current Source Density (CSD), and Multi-Unit Activity (MUA). Features include signal ', ...
        'filtering by frequency, event marking, and building average traces from events. ', ...
        'The data packaging format idea comes from Andrey Zakharov. For updates, visit github ', ...
        'ta3map EasyViewer and for data format information, see github AndreyZakharovExp.'];

    if exist(p.fullDir, 'dir')
        rmdir(p.fullDir, 's');
    end

    compiler.package.installer( ...
        { ...
            appExe, ...
            splashPath, ...
            fullfile(p.applicationDir, 'assets'), ...
            fullfile(p.applicationDir, 'configs'), ...
            fullfile(p.applicationDir, 'docs') ...
        }, ...
        fullfile(p.applicationDir, 'requiredMCRProducts.txt'), ...
        'ApplicationName', 'EasyView', ...
        'InstallerName', ['EasyView_' p.version '_setup'], ...
        'DefaultInstallationDir', 'C:\Program Files\EasyView', ...
        'RuntimeDelivery', 'installer', ...
        'Version', p.version, ...
        'AuthorName', 'Azat Gainutdinov', ...
        'AuthorEmail', 'ta3map@gmail.com', ...
        'Description', description, ...
        'InstallerIcon', fullfile(p.resources, 'icon_48.png'), ...
        'AddRemoveProgramsIcon', fullfile(p.resources, 'icon_48.png'), ...
        'InstallerLogo', fullfile(p.resources, 'easylogoinstaller.png'), ...
        'InstallerSplash', fullfile(p.resources, 'easylogo.png'), ...
        'OutputDir', p.fullDir);
end
